<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ProgramDesigner.Core\ProgramDesigner.Core.csproj" />
    <ProjectReference Include="..\ProgramDesigner.Infrastructure\ProgramDesigner.Infrastructure.csproj" />
    <ProjectReference Include="..\ProgramDesigner.Application\ProgramDesigner.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
